name: Trivy Container Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      # リポジトリのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Compose のセットアップ
      - name: Start Docker Compose services
        run: docker compose build --pull app

      # Trivyでコンテナイメージをスキャン
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8
        with: 
            image-ref: 'awesometodo:latest'
            format: 'table'
            vuln-type: 'os,library'
            severity: 'HIGH,CRITICAL'
            output: 'trivy-report.txt'
      
      - name: Run Trivy nginx image scan
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8
        with: 
            image-ref: 'nginx:1.19.0-alpine'
            format: 'table'
            vuln-type: 'os,library'
            severity: 'HIGH,CRITICAL'
            output: 'trivy-nginx-report.txt'

      # スキャンレポートをGitHub Actionsのアーティファクトとして保存
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: |
            trivy-report.txt
            trivy-nginx-report.txt
